package eu.df.jiffybox.internal;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonSetter;
import eu.df.jiffybox.models.Response;

/**
 * A response is generated by each request. It consists of messages and a result.
 *
 * @param <T> The responses result type.
 */
@JsonAutoDetect
class ErrorResponse<T> extends Response<T> {

    public ErrorResponse() {
        // Provide default constructor for jackson.
    }

    /**
     * Set the result.
     *
     * @param result The result.
     */
    @JsonSetter("result")
    public void setResult(final boolean result) {
        this.result = null;
    }
}