package eu.df.jiffybox.models;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;

import java.util.ArrayList;
import java.util.List;

/**
 * A response is generated by each request. It consists of messages and a result.
 *
 * @param <T> The responses result type.
 */
@JsonAutoDetect
public class Response<T> extends PrintableModel {

    /**
     * The result.
     */
    @JsonProperty("result")
    private T result = null;

    /**
     * A list of messages.
     */
    @JsonProperty("messages")
    private List<Message> messages = new ArrayList<>();

    /**
     * Get the list of messages.
     *
     * @return The list of messages.
     */
    @JsonProperty("messages")
    public List<Message> getMessages() {
        return messages;
    }

    /**
     * Set the messages.
     *
     * @param messages The messages.
     */
    @JsonSetter("messages")
    public void setMessages(final List<Message> messages) {
        this.messages = messages;
    }

    /**
     * Get the responses result as the previously defined type.
     *
     * @return The result.
     */
    @JsonProperty("result")
    public T getResult() {
        return result;
    }

    /**
     * Set the result.
     *
     * @param result The result.
     */
    @JsonSetter("result")
    public void setResult(final T result) {
        this.result = result;
    }
}
